# NOTE:
#   1. build with:
#       a. only ttf
#       $ npm run build -- ttf::shevska
#       b. build all (ttf, woff, css)
#       $ npm run build -- contents::shevska

[buildPlans.shevska]
# name of the font-family
family = "Shevska"
spacing = "normal"
serifs = "sans"

  # glyphs for the three different Slopes (Upright, Italic, Oblique) {{{
  [buildPlans.shevska.variants]

    [buildPlans.shevska.variants.design]
    # alpha-numberics {{{
    # alphabets {{{
    # latin {{{
    # majuscule {{{
    capital-a = "straight-top-serifed"

    # slight disconnection in the midddle
    capital-b = "standard-interrupted-unilateral-serifed"
    # use symmetrical serif in contrast to B
    capital-d = "more-rounded-bilateral-serifed"

    capital-c = "unilateral-inward-serifed"

    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"

    # avoid similarity with C
    capital-g = "toothless-corner-serifless-hooked"

    capital-h = "serifless"
    capital-i = "serifed"

    # elongated with a pronounced, hooked tail sans serif
    capital-j = "descending-serifless"

    # curly with a light foot
    capital-k = "curly-bottom-right-serifed"

    capital-m = "slanted-sides-hanging-motion-serifed"
    capital-n = "asymmetric-motion-serifed"

    capital-p = "open-motion-serifed"
    capital-r = "standing-open-motion-serifed"

    capital-q = "detached-tailed"

    # with a slight upper-right bend
    capital-s = "unilateral-inward-serifed"

    capital-t = "serifless"

    capital-u = "toothed-serifless"
    capital-v = "straight-motion-serifed"
    capital-w = "curly-serifless"

    capital-x = "straight-motion-serifed"

    capital-y = "straight-serifless"
    capital-z = "straight-top-serifed-with-horizontal-crossbar"
    # }}}

    # minuscule {{{
    a = "double-storey-toothless-corner"

    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"

    e = "rounded"

    # extended tail and elevated crossbar for the ultimate gothic look
    f = "flat-hook-extended-crossbar-at-x-height"

    g = "single-storey-flat-hook-earless-corner"
    h = "straight-serifless"

    i = "hooky"

    j = "flat-hook-serifless"
    k = "symmetric-touching-serifless"

    l = "hooky"

    # one single continuous arch (perfect symmetry)
    m = "earless-single-arch-short-leg-serifless"

    # cornered, upper-left
    n = "earless-corner-straight-serifless"

    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "compact-serifless"

    t = "hookless-asymmetric-short-neck"

    u = "toothless-corner-serifless"

    # pairwise distinguishing styles for |v| and |w|
    v = "curly-serifless"
    w = "straight-vertical-sides-serifless"

    x = "straight-serifless"
    y = "straight-turn-serifless"

    z = "straight-serifless-with-crossbar"
    # }}}
    # }}}

    eszet = "traditional"

    # Greek {{{
    # majuscule lambda & majuscule delta
    turn-v = "straight"
    # minuscule lambda
    lower-lambda = "straight-turn"

    lower-alpha = "crossing"
    lower-delta = "flat-top"
    capital-gamma = "top-right-serifed"
    lower-xi = "flat-top"
    lower-mu = "toothed-serifless"
    lower-iota = "serifed-diagonal-tailed"
    # }}}

    # cryllic {{{
    #cyrl-ka = "symmetric-connected-motion-serifed"

    cyrl-capital-u = "cursive-serifless"
    # }}}
    # }}}

    # numbers {{{
    # 0 {{{
    # a more rounded 0, better distinguishable from O and o
    zero = "oval-reverse-slashed"

    #       zero = "reverse-slashed"
    # }}}

    # 1 {{{
    # a very pronounced, slanted hook
    one = "no-base-long-top-serif"

    #       # a pixelated hook
    #       #       possible confusion with:
    #       #       1.  straight |l|
    #       #       2.  upper-left hooked |l|
    #       one = "nobase-flat-top-serif"
    # }}}

    # the straights {{{
    two = "straight-neck"
    six = "straight-bar"
    nine = "straight-bar"
    # }}}

    three = "flat-top"
    four = "semi-open-non-crossing"
    five = "oblique-upper-left-bar"
    eight = "crossing-asymmetric"

    # 7 {{{
    #       # with a natural curve of the body
    #       seven = "bend-crossbar"

    #       seven = "curly-crossbar"

    seven = "straight-serifless-crossbar"
    # }}}
    # }}}
    # }}}

    # symbols {{{
    # dev {{{
    ampersand = "upper-open"
    asterisk = "turn-penta-low"

    # "()" {{{
    paren = "normal"
    # }}}

    # "{}" {{{
    #       brace = "curly"
    brace = "curly-flat-boundary"
    # }}}

    #       underscore = "above-baseline"
    # underscore should be low enough to simulate a space
    underscore = "low"

    punctuation-dot = "square"
    # }}}

    # UNIX {{{
    tilde = "low"

    # stretches beyond normal caps -> distinguish between alpha-nums
    dollar = "open"

    # elevated comma
    #   ->  clearly distinguishable between backquote and double quotes
    ascii-single-quote = "raised-comma"

    bar = "force-upright"

    #       at = "threefold"
    at = "compact"

    # regards from Regex
    question = "corner-flat-hooked"


    # percent, aka, the zsh user-prompt {{{
    # a light connection between the slash and upper-left ring
    percent = "rings-continuous-slash-also-connected"

    #       percent = "rings-segmented-slash"
    # }}}

    # [z|ba]sh root-prompt
    number-sign = "slanted-open"
    # }}}

    # niche {{{
    pilcrow = "low"
    ascii-grave = "straight"
    caret = "high"

    # ligature for *-or-not-equal-to comparisons
    lig-ltgteq = "slanted"
    # }}}
    # }}}

  # ligatures {{{
  [buildPlans.shevska.ligations]
  #     inherits = "default-calt"

  #     # discretionary ligatures
  #     inherits = "dlig"

  enables = ["center-ops", "arrow", "arrow2", "trig", "eqeqeq", "eqeq", "ineq", "exeqeq", "exeqeq-dotted", "eqexeq", "eqexeq-dotted", "eqexeq-dl", "eqexeq-dl-dotted", "exeq", "exeq-dotted", "tildeeq", "eqslasheq", "slasheq", "ltgt-ne", "ltgt-diamond", "brst", "plusplus", "kern-dotty", "logic", "llgg", "llggeq", "dot-as-operator", "lteq-as-arrow", "gteq-as-co-arrow", "html-comment", "colon-greater-as-colon-arrow", "brace-bar", "brack-bar"]

  disables = []
  # }}}

# what to build {{{
# weight {{{
# default {{{
#       [buildPlans.shevska.weights.thin]
#       shape = 100
#       menu = 100
#       css = 100
#
#       [buildPlans.shevska.weights.extralight]
#       shape = 200
#       menu = 200
#       css = 200
#
#       [buildPlans.shevska.weights.light]
#       shape = 300
#       menu = 300
#       css = 300
#
#       [buildPlans.shevska.weights.regular]
#       shape = 400
#       menu = 400
#       css = 400
#
#       [buildPlans.shevska.weights.medium]
#       shape = 500
#       menu = 500
#       css = 500
#
#       [buildPlans.shevska.weights.semibold]
#       shape = 600
#       menu = 600
#       css = 600
#
#       [buildPlans.shevska.weights.bold]
#       shape = 700
#       menu = 700
#       css = 700
#
#       [buildPlans.shevska.weights.extrabold]
#       shape = 800
#       menu = 800
#       css = 800
#
#       [buildPlans.shevska.weights.heavy]
#       shape = 900
#       menu = 900
#       css = 900
# }}}

[buildPlans.shevska.weights.regl]
shape = 417
menu = 417
css = 417

[buildPlans.shevska.weights.emph]
shape = 741
menu = 741
css = 741
# }}}

[buildPlans.shevska.widths.lounger_]
shape = 576
menu = 7
css = "expanded"

[buildPlans.shevska.slopes.upright]
angle = 0.0
shape = "upright"
menu = "upright"
css = "normal"
# }}}

# vim: filetype=toml foldmethod=marker
