[buildPlans.shevska]
family = "Shevska"
spacing = "normal"
serifs = "sans"

[buildPlans.shevska.variants.design]
# alpha-numberics {{{
# alphabets {{{
diacritic-dot = "square"

# latin {{{
# majuscule {{{
capital-a = "straight-top-serifed"

# slight disconnection in the midddle
capital-b = "standard-interrupted-unilateral-serifed"
# use symmetrical serif in contrast to B
capital-d = "more-rounded-bilateral-serifed"

capital-c = "unilateral-inward-serifed"

capital-e = "top-left-serifed"
capital-f = "top-left-serifed"

# avoid similarity with C
capital-g = "toothless-corner-serifless-hooked"

capital-h = "serifless"
capital-i = "serifed"

# elongated with a pronounced, hooked tail sans serif
capital-j = "descending-serifless"

# curly with a light foot
capital-k = "curly-bottom-right-serifed"

capital-l = "motion-serifed"

capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"

capital-p = "open-motion-serifed"
capital-r = "standing-open-motion-serifed"

capital-q = "detached-tailed"

# with a slight upper-right bend
capital-s = "unilateral-inward-serifed"

capital-t = "serifless"

capital-u = "toothed-serifless"
capital-v = "straight-motion-serifed"
capital-w = "curly-serifless"

capital-x = "straight-motion-serifed"

capital-y = "straight-serifless"
capital-z = "straight-top-serifed-with-horizontal-crossbar"
# }}}

# minuscule {{{
a = "double-storey-toothless-corner"

b = "toothless-corner-serifless"
d = "toothless-corner-serifless"

e = "rounded"

# extended tail and elevated crossbar for the ultimate gothic look
f = "flat-hook-extended-crossbar-at-x-height"

g = "single-storey-flat-hook-earless-corner"
h = "straight-serifless"

i = "hooky"

j = "flat-hook-serifless"
k = "symmetric-touching-serifless"

l = "hooky"

# one single continuous arch (perfect symmetry)
m = "earless-single-arch-short-leg-serifless"

# cornered, upper-left
n = "earless-corner-straight-serifless"

p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "compact-serifless"

t = "hookless-asymmetric-short-neck"

u = "toothless-corner-serifless"

# pairwise distinguishing styles for |v| and |w|
v = "curly-serifless"
w = "straight-vertical-sides-serifless"

x = "straight-serifless"
y = "straight-turn-serifless"

z = "straight-serifless-with-crossbar"
# }}}
# }}}

eszet = "traditional-descending-serifless"

# Greek {{{
# majuscule lambda & majuscule delta
turn-v = "straight"
# minuscule lambda
lower-lambda = "straight-turn"

lower-alpha = "crossing"
lower-delta = "flat-top"
capital-gamma = "top-right-serifed"
lower-xi = "flat-top"
lower-mu = "toothed-serifless"
lower-iota = "serifed-diagonal-tailed"
# }}}

# cryllic {{{
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "curly"
cyrl-capital-ka = "symmetric-touching-top-left-serifed"
cyrl-ka = "curly-serifless"
cyrl-capital-ya = "standing-open-serifless"
cyrl-ya = "straight-open-serifless"

cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "serifless"

cyrl-yeri = "round"
cyrl-yery = "cursive"

cyrl-el = "straight"
cyrl-em = "hanging-serifless"
cyrl-en = "serifless"

cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-capital-u = "cursive-serifless"
# }}}
# }}}

# numbers {{{
zero = "oval-reverse-slashed"

# a very pronounced, slanted hook
one = "no-base-long-top-serif"

# straight neck
two = "straight-neck"
six = "straight-bar"
nine = "straight-bar"

three = "flat-top"
four = "semi-open-non-crossing"
five = "oblique-upper-left-bar"
eight = "crossing-asymmetric"

seven = "straight-serifless-crossbar"
# }}}
# }}}

# symbols {{{
punctuation-dot = "square"
# descend to simulate space
underscore = "low"

# dev {{{
ampersand = "upper-open"
asterisk = "turn-penta-low"

paren = "normal"  # ()
brace = "curly-flat-boundary"  # {}

tilde = "low"

caret = "high"
dollar = "interrupted"
percent = "rings-continuous-slash-also-connected"
number-sign = "slanted-open"

# elevated comma
#   ->  clearly distinguishable between backquote and double quotes
ascii-single-quote = "raised-comma"

bar = "force-upright"
# }}}

at = "compact"
question = "corner-flat-hooked"
ascii-grave = "straight"  # backtick

# misc {{{
cent = "open"
partial-derivative = "curly-bar"
lower-eth = "straight-bar"
micro-sign = "tailed-serifless"

pilcrow = "low"  # paragraph-indicator
# }}}
# }}}

# ligatures {{{
lig-ltgteq = "flat"  # leq, geq
lig-neq = "vertical-dotted"  # !=
lig-equal-chain = "with-notch"  # ==
lig-hyphen-chain = "with-notch"  # --
lig-double-arrow-bar = "with-notch"  # =>
lig-single-arrow-bar = "with-notch"  # ->

[buildPlans.shevska.ligations]
inherits = "dlig"  # discretionary ligature

disables = []
# }}}

# build target {{{
# weight {{{
# NOTE:
#   1. common aliases:
#       thin: 100
#       extralight: 200
#       light: 300
#       regular: 400
#       medium: 500
#       semibold: 600
#       bold: 700
#       extrabold: 800
#       heavy: 900

[buildPlans.shevska.weights.base]
shape = 417
menu = 417
css = 417

[buildPlans.shevska.weights.plus]
shape = 741
menu = 741
css = 741
# }}}

[buildPlans.shevska.widths.exact_]
shape = 537  # anything within (500, 600) seems fine
menu = 5
css = "normal"

[buildPlans.shevska.slopes.upright]
angle = 0.0
shape = "upright"
menu = "upright"
css = "normal"
# }}}

# vim: filetype=toml foldmethod=marker
